### ISSUE TITLE
Problems with NPM resolution

### ISSUE THREAD

**Issue by gaydenko** [ThoughtWorksInc/todo#1]
Hi!
`indexHtml` results in 
```
[error] module.js:472
[error]     throw err;
[error]     ^
[error] 
[error] Error: Cannot find module 'internal/fs'
[error]     at Function.Module._resolveFilename (module.js:470:15)
[error]     at Function.Module._load (module.js:418:25)
[error]     at Module.require (module.js:498:17)
[error]     at require (internal/module.js:20:19)
[error]     at evalmachine.<anonymous>:18:20
[error]     at Object.<anonymous> (/wrk/z/todo/project/target/node-modules/webjars/npm/node_modules/graceful-fs/fs.js:11:1)
[error]     at Module._compile (module.js:571:32)
[error]     at Object.Module._extensions..js (module.js:580:10)
[error]     at Module.load (module.js:488:32)
[error]     at tryModuleLoad (module.js:447:12)
java.lang.RuntimeException: Problems with NPM resolution. Aborting build.
```

**Comment by Atry** [comment]
Can't reproduct

**Comment by fineline** [comment]
Simlar error here, on macOS 10.12.3, sbt 0.13.11. I clone the repo, then run

sbt indexHtml

And get this error:

[error] module.js:472
[error]     throw err;
[error]     ^
[error] 
[error] Error: Cannot find module 'internal/fs'
[error]     at Function.Module._resolveFilename (module.js:470:15)
[error]     at Function.Module._load (module.js:418:25)
[error]     at Module.require (module.js:498:17)
[error]     at require (internal/module.js:20:19)
[error]     at evalmachine.<anonymous>:18:20
[error]     at Object.<anonymous> (/Users/tstewart/todo/project/target/node-modules/webjars/npm/node_modules/graceful-fs/fs.js:11:1)
[error]     at Module._compile (module.js:571:32)
[error]     at Object.Module._extensions..js (module.js:580:10)
[error]     at Module.load (module.js:488:32)
[error]     at tryModuleLoad (module.js:447:12)
java.lang.RuntimeException: Problems with NPM resolution. Aborting build.
        at scala.sys.package$.error(package.scala:27)
        at com.typesafe.sbt.jse.SbtJsEngine$$anonfun$2$$anonfun$3.apply(SbtJsEngine.scala:114)
        at com.typesafe.sbt.jse.SbtJsEngine$$anonfun$2$$anonfun$3.apply(SbtJsEngine.scala:91)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
        at com.typesafe.sbt.jse.SbtJsEngine$$anonfun$2.apply(SbtJsEngine.scala:122)
        at com.typesafe.sbt.jse.SbtJsEngine$$anonfun$2.apply(SbtJsEngine.scala:86)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (todo/web-assets:jseNpmNodeModules) Problems with NPM resolution. Aborting build.
[error] Total time: 3 s, completed 22/03/2017 8:57:52 AM

**Comment by Atry** [comment]
Looks like Node.js bugs: https://stackoverflow.com/questions/40308623/cannot-find-module-internal-fs-afer-upgrading-to-node-7

**Comment by fineline** [comment]
I can confirm that one of the solutions on that SO question worked for me:

$ sudo n 6.9.1
$ sudo npm -g install npm@next
$ sudo n stable

**Comment by Atry** [comment]
@fineline Congratulation!

**Comment by gaydenko** [comment]
I'm sure it would be more handy for all curious to make the app working with modern Node version. Of course, in the situation plenty of other apps do work under the modern Node (7.7.3 at my case), it rather difficult to expect I will downgrade Node (with the risk to break something else) :)
